### PR TITLE
🏗️  Merge webhook and controller into one container and update tooling 

### PR DESCRIPTION
**Pull request by dergeberl**
This PR contains the following changes:
- Merge the  webhook and controller into one container
  - Use the gardener extension webhook setup and also handle the certificates with that
- Refactor helm chart and overall cleanup
- Remove Earthly and add a Makefile which is also used in https://github.com/stackitcloud/gardener-extension-shoot-flux
  - Update also the github actions

Co-authored-by: @timebertt

### CODE REVIEW

**Comment by SimonKienzler** [comment]
I mean, I'm fine switching to `make`, but I now cannot run `make verify-extended` locally AND in the GitHub Action. One of both will always fail because of the generated `base64` encoded `helmChart` in the `controller-registration.yaml`. We should come up with a way to make this work reliable both locally and in CI.

**Comment by timebertt** [comment]
Let's look at the controllerregistration generation together on Friday :)

**Comment by timebertt** [comment]
@SimonKienzler can you try again with the latest commit?
I think you might be running an old helm version that generates a different tar than what is generated by the helm version installed by `tools.mk` (`v3.11.2`). The make dependency on the helm tool was missing, so it used whatever `helm` binary was found on your `PATH`.

With the latest commit, I can run `make generate` and `make check` successfully on my host machine and in a container successfully without any differences:
```
$ docker run --rm -it -v $PWD:/go/src/github.com/stackitcloud/gardener-extension-acl --workdir /go/src/github.com/stackitcloud/gardener-extension-acl golang:1.21
root@1be2078e32f5:/go/src/github.com/stackitcloud/gardener-extension-acl# make init
...
root@1be2078e32f5:/go/src/github.com/stackitcloud/gardener-extension-acl# make clean-tools-bin generate
...
root@1be2078e32f5:/go/src/github.com/stackitcloud/gardener-extension-acl# make clean-tools-bin check
...
root@1be2078e32f5:/go/src/github.com/stackitcloud/gardener-extension-acl# git status
On branch hackathon/tools-setup
Your branch is up to date with 'origin/hackathon/tools-setup'.

nothing to commit, working tree clean
```

**Comment by SimonKienzler** [comment]
Unfortunately, it still doesn't work. You were right about the `helm` version, and I can confirm that the container-based generation produces no diff to the currently committed `base64` string, but running `make generate` locally still produces a diff, even after a cleansing of the tools folder.

I'll dig some more, it's a me problem after all 😅

**Review by SimonKienzler — APPROVED** [review]

**Pull request merged**
