### PR TITLE
update go dependencies

### PR DESCRIPTION
**Pull request by dergeberl**

### CODE REVIEW

**Review by breuerfelix — APPROVED** [review]

**Review by nschad — APPROVED** [review]

**Comment by SimonKienzler** [comment]
@dergeberl this PR has been approved for a while. I have locally updated theis branch to Go 1.20, bumped the golangci-lint version and fixed some linter issues. Can I hijack this PR for the changes, or should we get your changes in and then I'll open a new PR with mine?

**Comment by dergeberl** [comment]
I am fine with both ways!

**Review by nschad — CHANGES_REQUESTED** [review]
needs rebase!

**Comment by SimonKienzler** [comment]
Superseded by #27

**Pull request closed without merging**
